### ISSUE TITLE
Testing in app

### ISSUE THREAD

**Issue by kphretiq** [citruspi/Flask-Analytics#4]
This is not a bug report, but a request for clarification.

I've installed Flask-Analytics in my app using pip.

I have add GOOGLE_ANALYTICS_ID in app.config.

I have included {{ analytics }} in the body of my index.html template.

I was expecting to see some interesting new text inserted into my html output, but I note no differences.

What should I expect to see in my html output, if anything?

**Comment by citruspi** [comment]
You should be seeing the analytics code snippet for Google Analytics. I've updated the readme to include a sample result.

(Note that the code in the readme is for the new 0.5.0 release, and isn't compatible with previous versions. If you're still using a previous version, you'd want to stick with the `GOOGLE_ANALYTICS_ID` key.)

If you're still using the older version, you could try

```python
{{ analytics.google }}
```

However, I would recommend updating to the new version.

**Comment by kphretiq** [comment]
Using pip, uninstalled and re-installed Flask-Analytics got error:

 from flask_analytics.providers.gosquared import GoSquared
10:00:57 web.1  | ImportError: No module named providers.gosquared

Sorry to be a pain.

**Comment by shamrt** [comment]
> No module named providers.gosquared

This is because the package on PyPI, as it stands, is missing the providers directory. 

@citruspi, you may want to check to ensure that you've properly submitted everything to the PyPI service.

**Comment by scottydelta** [comment]
@shamrt , installing using the source from github also dint resolve the following error. I had to manually copy the providers directory in lib/python2.7/site-packages/Flask_Analytics-0.5.0-py2.7.egg/flask_analytics/

    No module named providers.gosquared

**Comment by jdp** [comment]
+1 for fixing the PyPI release, without the providers directory the extension is crippled.

**Comment by loisaidasam** [comment]
:+1:

**Comment by citruspi** [comment]
Hey, so now that #5 is merged, I just need to bump the version and upload the new version to PyPi.

I'm going to re-open this issue until the patched version is live.

**Comment by citruspi** [comment]
Cool, so version `0.5.2` has been pushed to PyPi and should be good.

If you run into any issues, just open an issue.
