### ISSUE TITLE
Python 3 compatability?

### ISSUE THREAD

**Issue by jeffwidman** [citruspi/Flask-Analytics#6]
Any interest/timeline in updating to use Python 3? The flask project I'm working on uses Python 3.4, probably will switch to python 3.5 soon.

**Comment by citruspi** [comment]
No timeline, but I am interested; I've personally switched to Python 3 and I can't imagine it would require a lot of changes.

I'll take a look sometime this weekend or next week.

**Comment by citruspi** [comment]
Hey, support for Python 3 was pushed as part of version 0.5.5 and is now live on PyPi.

**Comment by jeffwidman** [comment]
:+1:
